# Generated by Django 3.2.6 on 2021-08-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='dateOfReservation',
            new_name='reservation_date',
        ),
    ]
